set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_POSITION_INDEPENDENT_CODE ON) # -fPIC
set(CMAKE_EXPORT_COMPILE_COMMANDS ON) # for clang-tidy

if (CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    add_compile_options("-Wall -Wextra")
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    add_compile_options("-W4")
endif ()